[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'Lokaltog/vim-powerline'

[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'mhinz/vim-signify'

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'cynipe/editorconfig-vim'
rev = 'add-other-charset-support'

[[plugins]]
repository = 'haya14busa/incsearch.vim'

[[plugins]]
repository = 'scrooloose/nerdtree'


